# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Google-Mobile-Ads-SDK'
target 'Section22.122(AdmobBannersAds)' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Section22.122(AdmobBannersAds)

  target 'Section22.122(AdmobBannersAds)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Section22.122(AdmobBannersAds)UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
